imports:
    - { resource: parameters.yml }
    - { resource: "@CoreBundle/Resources/config/security_oauth.yml" }
    - { resource: "@CoreBundle/Resources/config/services_oauth.yml" }
    - { resource: "@CoreExtraBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@EcommerceBundle/Resources/config/services.yml" }
    - { resource: "@FrontBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        core: %core%
        twig_global: "@twig.global"  
        
# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true
#        dql:
#            numeric_functions:
#                DISTANCE: CoreBundle\Functions\DistanceFunction
#            string_functions:
#                GroupConcat: CoreBundle\Functions\GroupConcatFunction
        entity_managers:
            default:
                auto_mapping: true
                # New custom filter
                filters:
                    oneLocale:
                        class: A2lix\I18nDoctrineBundle\Doctrine\ORM\Filter\OneLocaleFilter
                        enabled: true
                        
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: '%kernel.debug%'
    bundles:
        [ CoreBundle, CoreExtraBundle, AdminBundle, BlogBundle, EcommerceBundle , FrontBundle ]
    node: "%node_path%"
    filters:
        cssrewrite:
            apply_to: ".css$"
        less:
            node: "%node_path%"
            node_paths: ["%node_modules_path%"]
            apply_to: ".less$"

# OAuth login social networks  
hwi_oauth:
     #name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [user]
    target_path_parameter: /
    resource_owners:
        test_connect:
            type:                oauth2
            client_id:           4_1f10ptc6pyqs0gkoog0cwcwokwkw04gsww4gsss8ogcswo48w4
            client_secret:       43dqxml7kieck4ock04o0kow4c4k08s44kc0o008oosk880swk
            access_token_url:    http://oauth.sasturain.com/oauth/v2/token
            authorization_url:   http://oauth.sasturain.com/oauth/v2/auth
            infos_url:           http://oauth.sasturain.com/me
            scope:               "read"
            user_response_class: HWI\Bundle\OAuthBundle\OAuth\Response\PathUserResponse
            paths:
                identifier: id
                nickname:   username
                realname:   username
        twitter:
            type:                twitter
            client_id:           WVdAUmB1txAvLPw8Y5l0ImLp1
            client_secret:       DyaY1TkbFh1b643irHCs0pbMo009CWrwuD34LQvEqkvTZHfdAi
        google:
            type:                google
            client_id:           43533348693-5cc8rtt9u836lenact1l4dtprenq0m0j.apps.googleusercontent.com
            client_secret:       xLP8Qcvqn3rBEMy5btOrSxfv
            scope:               "email profile"
            options:
                access_type:     offline
                approval_prompt: force
                display:         popup
                login_hint:      sub
        facebook:
            type:                facebook
            client_id:           1743100236016760
            client_secret:       7fcf396e2bcdfeff4a430c25d5405e84
            scope:               "email"
            options:
                display: popup 
        instagram:
            type:                instagram
            client_id:           13943a65e997457da0adb66abb4ef5c2
            client_secret:       56a8dc30590d47f496d65623d60f100e
            scope:               basic
               
jms_i18n_routing:
    default_locale: es
    locales: [es, en, de]
    strategy: prefix_except_default                 
a2lix_i18n_doctrine:
    manager_registry: doctrine       # [1]
a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [es, en, de]      # [1-a]
    default_locale: es             # [1-b]
    required_locales: [es, en, de]         # [1-c]
    manager_registry: doctrine     # [2]
    templating: "CoreBundle:Base:default.tabs.html.twig"      # [3]
    
    
core:
    extended_layout: 'FrontBundle:Base:layout.html.twig'
    server_base_url: 'http://sasturain.dev'
    admin_email: admin@admin.com
# If you want add item in admin menu use this example
# dashboard:
#    icon_class: 'fa fa-dashboard'
#    label: 'dashboard'
#    options:
#        menuitems: core_menuitem_index
#        sliders: core_slider_index
admin:
    admin_menus:  ~
    company_menus:  ~
    apis:
        google_analytics:
            options:
                application_name: Analitycs integración
                oauth2_client_id: 43533348693-s4rafifpr1o07gja2kgnfbhf4tjq2g0f.apps.googleusercontent.com
                oauth2_client_secret: lo04F5hvUi_gPaAxyucY70jy
                oauth2_redirect_uri: 'http://sasturain.dev/admin/analytics'
                developer_key: AIzaSyCda_bsJ-kEa1M1DJenwKfUfyLVlVKuC6I
 
blog:
#    fixture_data: true    

ecommerce:
#    fixture_data: true
#    currency_symbol: €
#    advert_unit_price: 1
#    vat: 0.21
#    special_percentage_charge: 0
#    delivery_expenses_type: by_percentage
#    delivery_expenses_percentage: 0
#    bank_account: 'ESXX XXX XXXX XXXX XXXX XXXX'

# Translation Configuration
asm_translation_loader:
    driver: orm
    history: true # default false
    database:
        entity_manager: default
                
dcs_dynamic_discriminator_map:
    mapping:
        baseactor:
            entity: CoreBundle\Entity\BaseActor
            map:
                Actor: CoreBundle\Entity\Actor
