core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /
    
admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

#blog:
#    resource: "@BlogBundle/Resources/config/routing.yml"
#    prefix:   /
    
ecommerce:
    resource: "@EcommerceBundle/Resources/config/routing.yml"
    prefix:   /